sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: VwPe9orPoYLygtc3mp7fG9xo8KnrTFZwn0nAdlUSTzF/ls9S7lneeHkpHHUmGoyZzPNObtfxfvVMCrwC8jDdixiO80FPYk74EpZJwIF6sz378k7oGNXMDLVzd+I/xeTOchhxVndS95Cx1dofCT7GnVKGBnVgWmJPFBvMssU0isON8IgDJH4oCmB1fU8m5RPfrdpAWzASKbtqVy/ptITlh/qA6sE9Fs4rlzhd+hFppbVI8NUhStjW23/wuUxMYZLr/gvVF0e3wkpiWOU92n4RzhWkS/dWIZZFwCZQNmHfDlfIL9yxbvcpQp1fGMIQzm0rRliPgpn7zl65fhMjkaxHNv/Mug+ViLnL0DM5HDUjGc9a2W4VZH6gdDg0mqZbr+0QfCOQGU48osedJHLszrkktw407bxRY/MnoMoBSJ/tLBw91H5Om+v9oghjOrOnbbeqMIx3zvf8Nx+/C7jxQNMjdHvjAasitw+w2HOo91SFNfDahkD9A6Zk2zaRxfAal6YPMsGFkf6kVPmS7y89BJ8r9NboWcRtW79NNgC282ygnaRpPFi9DEagJdcih1GyaQEaEwd0dGH5RLPS7Lb/ysGqthaDjGptmh67lQn9C9lHdn1QNo+uo8iCUpDKhEVLCU6c3TshmzRf2HLUbPkO1KKgbzRwT8zq7q5d6DoaakRzsGw=
  app: call-by-meaning
  on:
    repo: cbmjs/cbm-engine
    condition: $TRAVIS_OS_NAME = osx
  skip_cleanup: true
notifications:
  email: false
after_success:
- nyc report --reporter=text-lcov > coverage.lcov && codecov
