name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🧪 Run test script
        run: npm test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
