name: CI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: npm test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          CI: true
      - name: Generate coverage report
        run: npm run generate-report
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.lcov
